### PR TITLE
Refactor add small dashboard card button

### PR DESCRIPTION
**Pull request by jun-loke**
# General info

**Issue number**: N/A

**Task description**: 

 - Refactor DashBoardCard to have Grid container around children
   - adapt all HOC that use DashboardCards accordingly and update their tests 
 - Create SmallCardButton and ButtonInfo objects for the dashabord card
 - Added conditional rendering for SmallCardButton using new optional button prop

 
 
| Original   | Updated|
|:---------------:|:---------------:|
|n/a |image
 |

# Testing

**Test coverage**:

# Additional notes

**Note to reviewers**:

To try this out, add the following to a card. I used the cards in StreamDetailsPageContents, since that's where these will be used, though these components are undergoing changes in #430 so the buttonCard will be implemented there or afterwards
``` javascript
+ import ButtonInfo from "../general/dashboard/ButtonInfo";
```
``` javascript
  const button = new ButtonInfo(
    `somePathName/${someDeviceInfo.serialNumber}`,
    {device: someDeviceInfo},
    "buttonTitle"
  );

<DashboardCard title="someTitle" button={button}>
```

**To do before merging**:

### CODE REVIEW

**Comment by felixlapierre** [comment]
Tried clicking the view device button, got a `TypeError: channels is undefined` error. 🍍

**Review by gdzooks — COMMENTED** [review]
code looks good to me but unfortunately the button doesn't seem to be working on my end? i get this:
image

looking at how you coded the button i feel like it SHOULD work?
~~if you could do the receiver card as well while you're here that'd be pretty cash money-~~

**Review by felixlapierre — APPROVED** [review]
Im cool w/ merging this! Tho we should merge with the view device button on both the sender and receiver cards (or on neither)

**Review by gdzooks — APPROVED** [review]
same comment as felix! worst case if u dont add the button here i'll make myself a note to add it when i fix up #430 :3

**Comment by jun-loke** [comment]
@felixlapierre  @gdzooks 

1) The issue with cannot read property map of undefined is due to issue where the DeviceInfo being retrieved from the StreamInfo does not have all of the properties defined. This has been logged in #437 Pr will be up soon

2) @gdzooks  Since you're replacing the deviceCards on Stream details in #430 I'll leave that up to you

**Pull request merged**
