### PR TITLE
[#341] Create page

### LINKED ISSUE #341: Extract Page component from page components
- [ ] Close Create Page #350 
- [ ] Close #342 
- [ ] Close #343 
- [ ]  Close #344 
- [ ] Close #345 
- [ ] Close #346 
- [ ] Close #347 
- [ ] Close #348

### PR DESCRIPTION
**Pull request by jun-loke**
# General info

**Issue number**: #341 

**Task description**: 

 - Create Title Component
 - Create Page Component
 - Add corresponding tests
 - Update HeaderBar Component
 - Fix test for HeaderBar Component
 
 
| Original   | Updated|
|:---------------:|:---------------:|
| | |

# Testing

**Test coverage**:

# Additional notes

**Note to reviewers**:

**To do before merging**:
- [ ] Edit Changelog(if necessary)

### CODE REVIEW

**Review by gdzooks — APPROVED** [review]
simple enough PR. idm approving it as-is, testing is lovely and the changes are very clean!
only question i have is how the title component is gonna work with the buttons we have setup in certain title areas. `DeviceDetails` is a particular worry since there's a LOT going on in there

**Comment by jun-loke** [comment]
> simple enough PR. idm approving it as-is, testing is lovely and the changes are very clean!
> only question i have is how the title component is gonna work with the buttons we have setup in certain title areas. `DeviceDetails` is a particular worry since there's a LOT going on in there

@gdzooks 
Hmm for that we can add a prop that can allow us to toggle between options. Notably `DeviceList `already has a Titlearea(? can't quite remember the name) component which we could swap in.

As for `DeviceDetails`, discussion with the PM has lead to a redesign in which the pen/edit details will be in the device fields as shown in this mockup. Other than that, none of the other pages should have any issue with the title area
image

**Comment by gdzooks** [comment]
> @gdzooks
> Hmm for that we can add a prop that can allow us to toggle between options. Notably `DeviceList `already has a Titlearea(? can't quite remember the name) component which we could swap in.
> 
> As for `DeviceDetails`, discussion with the PM has lead to a redesign in which the pen/edit details will be in the device fields as shown in this mockup. Other than that, none of the other pages should have any issue with the title area
> image

right right that redesign slipped my mind thanks for reminding me! you have my easy 100% approval for this pr :tada:

**Review by felixlapierre — APPROVED** [review]
Looks good! 😄

**Pull request merged**
