### PR TITLE
Auth create stream bug

### PR DESCRIPTION
**Pull request by FGRCL**
# General info
Fix a bug in the frontend where the create stream operation to the API wouldn't use an authorization header

**Issue number**: N/A

**Task description**: 

 - Move the create stream operation to `StreamApi`
 - Add the authorization header to the axios post request
 
 
| Original   | Updated|
|:---------------:|:---------------:|
| | |

# Testing

**Test coverage**:
Moved the axios call test 

# Additional notes

**Note to reviewers**:

**To do before merging**:
- [ ] Edit Changelog(if necessary)

### CODE REVIEW

**Review by jun-loke — CHANGES_REQUESTED** [review]
Linter stuff but other than that looks good. Good catch

**Comment by pobudzey** [comment]
Tested with samples branch 277-Authentication and everything works perfectly

**Comment by FGRCL** [comment]
Alright, linting fixed

**Review by felixlapierre — APPROVED** [review]
LGTM! Thx for refactoring createStream into streamApi

**Review by jun-loke — APPROVED** [review]

**Pull request merged**
