### PR TITLE
[#344] Refactor Streamlist to Page

### LINKED ISSUE #344: Refactor StreamList Page to use Page component

### PR DESCRIPTION
**Pull request by jun-loke**
# General info

**Issue number**:  Closes #344

**Task description**: 

 - remove streamlist from CreateStream Page
 - Make StreamListPage to use Page component
 - Update testing

# Additional notes

**Note to reviewers**:

- Yes, it's normal to have two headerbars. The extra headerbar is from the Index.js page where we render a headerbar regardless of whether or not we are logged in. That entire file is being rewritten so I ddin't bother remove it for this PR, but you can check for yourself by removing the line

**To do before merging**:
- [ ] Edit Changelog(if necessary)

### CODE REVIEW

**Comment by felixlapierre** [comment]
Since the components to create stream are gone in the /Streaming page I can't create streams anymore, is there a workaround i'm not seeing? We can't merge to master if it removes the create stream functionality.

**Comment by jun-loke** [comment]
> Since the components to create stream are gone in the /Streaming page I can't create streams anymore, is there a workaround i'm not seeing? We can't merge to master if it removes the create stream functionality.

I'm splitting off Create stream to its own page. We can merge that one first. It's just more of a pain to do so I put it off till later

**Review by felixlapierre — DISMISSED** [review]

**Review by gdzooks — COMMENTED** [review]
code looks fine to me, render works as expected (extra header bar included)
ready to approve once sonarcloud quality gate passes

**Review by felixlapierre — APPROVED** [review]

**Review by gdzooks — APPROVED** [review]

**Comment by gdzooks** [comment]
( discussed merging despite coverage in slack. big changes coming with frontend auth will take care of coverage issues )

**Pull request merged**
