### PR TITLE
Add Bug Template

### PR DESCRIPTION
**Pull request by sharon-ho**
# General info

**Issue number**: N/A

**Task description**: 
- Added bug template to repo

# Testing

**Test coverage**:
N/A

# Additional notes

**Note to reviewers**:
N/A

**To do before merging**:
N/A

### CODE REVIEW

**Review by mohhef — APPROVED** [review]
Good initiative for everyone to follow the same template

**Review by jun-loke — APPROVED** [review]
That's a template. Why didn't you use the header notation tho? It's it easier to just have 
`# Section Title` instead of `**Section Title**`?

**Comment by sharon-ho** [comment]
> That's a template. Why didn't you use the header notation tho? It's it easier to just have
> `# Section Title` instead of `**Section Title**`?

@arejayelle I decided against it since bug reports tend to have the section titles as bolded instead of as headers, and we've been using this format casually for a while now (including during Minicap). Also because there are a lot of sections, the large font size and the fact that there are several successively seems a bit too overwhelming visually and seems to distract from the content itself.

This is what it would look like if section headers were used instead:
image

**Comment by sharon-ho** [comment]
@felixlapierre Now that the bug report template is merged, could you possibly add it as a template in the repo's settings?

**Pull request merged**
