### PR TITLE
[#348] Refactor CreateStream to own Page

### LINKED ISSUE #348: Extract CreateStreamPage to own component

### PR DESCRIPTION
**Pull request by jun-loke**
# General info

**Issue number**: Closes #348 

**Task description**: 

 - make independent component CreateStream
 - Add new page to router
 - link buttons
 - test
 
 
| Original   | Updated|
|:---------------:|:---------------:|
| | |

# Testing

**Test coverage**:

# Additional notes

**Note to reviewers**:

**To do before merging**:
- [ ] Edit Changelog(if necessary)

### CODE REVIEW

**Review by felixlapierre — DISMISSED** [review]

**Review by gdzooks — COMMENTED** [review]
is there a reason we're leaving the table for creating streams on the streaming page in addition to it getting its own page?
i think this PR would be more complete if we added a new stream button on the page and got rid of the creating streams table for the stream page. 
if we just want to get the big refactors out of the way without spending time fixing tests then i'm ready to approve if we add an issue for create stream appearing on 2 pages

**Comment by jun-loke** [comment]
> is there a reason we're leaving the table for creating streams on the streaming page in addition to it getting its own page?
> i think this PR would be more complete if we added a new stream button on the page and got rid of the creating streams table for the stream page.
> if we just want to get the big refactors out of the way without spending time fixing tests then i'm ready to approve if we add an issue for create stream appearing on 2 pages


@gdzooks 
I was keeping it because Felix didn't want the functionality to go missing on master. But it shouldn't be an issue if we merge them successively.
Deleted in 1d16811

**Review by felixlapierre — APPROVED** [review]

**Review by gdzooks — DISMISSED** [review]

**Review by gdzooks — COMMENTED** [review]
oh wait approved a bit too quickly - the change you've done has made the streaming page empty on my end? i thought the streaming page was supposed to have the table on its own + maybe a button to go to `Streaming/New`?
will merging https://github.com/bean-pod/switchboard/pull/360 after fix that? & the test coverage for #360?

**Comment by jun-loke** [comment]
> oh wait approved a bit too quickly - the change you've done has made the streaming page empty on my end? i thought the streaming page was supposed to have the table on its own + maybe a button to go to `Streaming/New`?

@gdzooks 
yes, the page doesn't exist any more because I deleted it. Since we will be having successive PRs, the page will not be missing for long, only the time between merging the two PRS

**Review by gdzooks — APPROVED** [review]
okeydokey counting on other PRs to bring back our beloved streamlist

**Pull request merged**
